#!/usr/bin/perl

use File::Basename;
use Cwd;
use Cwd 'abs_path';

$cwd  = abs_path( getcwd() );
$bdir = abs_path( dirname(__FILE__) );
require "$bdir/utility.pm";
config_init('cryosparc');

$notes = "usage: $0 arguments

installs cryosparc if needed
runs cryosparc server

";

## are license etc stored, if not, build up license info

### 1st get license

if ( !defined $$secrets{cryosparc_license} ) {
    my $ok = 0;
    my $license;
    while ( !$ok ) {
        $license = getinput( "Enter your cryosparc license:" );
        ## check license
        if ( $license !~ /^[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}$/ ) {
            print "This does not appear to be a valid license.\n";
            next;
        }
        $ok = 1;
    }
    $$secrets{cryosparc_license} = $license;
    secrets_write();
}

$extract = 0;

## download if needed
if ( !-e "$$config{cryosparc_downloads}/cryosparc_master.tar.gz" ||
     !-e "$$config{cryosparc_downloads}/cryosparc_worker.tar.gz" ) {
    ## download
    print message_header( "Downloading cryosparc\n*** This step may take a few minutes ***" );
    run_cmd( "cd $$config{cryosparc_downloads} && curl -L https://get.cryosparc.com/download/master-latest/$$secrets{cryosparc_license} -o cryosparc_master.tar.gz" );
    run_cmd( "cd $$config{cryosparc_downloads} && curl -L https://get.cryosparc.com/download/worker-latest/$$secrets{cryosparc_license} -o cryosparc_worker.tar.gz" );
    $extract = 1;
}

## verify user secrets
{
    my %req_secrets = (
        "cryosparc_install_email"      => "Cryosparc installation email address :"
        ,"cryosparc_install_username"  => "Cryosparc installation user name     :"
        ,"cryosparc_install_password"  => "Cryosparc installation password      :"
        ,"cryosparc_install_firstname" => "Cryosparc installation first name    :"
        ,"cryosparc_install_lastname"  => "Cryosparc installation last name     :"
        );

    my @req_secrets_ordered = (
        "cryosparc_install_email"
        ,"cryosparc_install_username"
        ,"cryosparc_install_password"
        ,"cryosparc_install_firstname"
        ,"cryosparc_install_lastname"
        );

    my @update;
    for my $k ( @req_secrets_ordered ) {
        if ( !exists $$secrets{$k} ) {
            push @update, $k;
        }
    }

    if ( @update ) {
        my %new_vals;
        do {
            print message_header( "Enter required cryosparc installation information" );
            for my $k ( @update ) {
                $new_vals{$k} = getinput( $req_secrets{$k} );
            }

            print message_header( "Verify inputs" );
            for my $k ( @update ) {
                print "$req_secrets{$k} $new_vals{$k}\n";
            }
            print line();
        } while ( !getareyousure( "" ) );

        for my $k ( @update ) {
            $$secrets{$k} = $new_vals{$k};
        }
        secrets_write();
    }
}

## do we need to extract & install

sub install {
    print message_header( "Installing cryosparc\n*** This step may take many minutes ***" );
    my $cmd = qq(
cd $$config{cryosparc_directory}/cryosparc_master && \\
yes 1 | ./install.sh --standalone \\
             --license $$secrets{cryosparc_license} \\
             --worker_path $$config{cryosparc_directory}/cryosparc_worker \\
             --cudapath $$config{cryosparc_cuda_path} \\
             --ssdpath $$config{cryosparc_directory} \\
             --initial_email "$$secrets{cryosparc_install_email}" \\
             --initial_password "$$secrets{cryosparc_install_password}" \\
             --initial_username "$$secrets{cryosparc_install_username}" \\
             --initial_firstname "$$secrets{cryosparc_install_firstname}" \\
             --initial_lastname "$$secrets{cryosparc_install_lastname}" \\
             --port $$config{cryosparc_port} && \\
$$config{cryosparc_directory}/cryosparc_master/bin/cryosparcm stop && \\
echo "export CRYOSPARC_MASTER_HOSTNAME=\$\(hostname -f\) >> $$config{cryosparc_directory}/cryosparc_master/config.sh
);
    run_cmd( $cmd, 0, 0, 1 );
}

sub extract {
    print message_header( "Extract cryosparc\n*** This step may take many minutes ***" );
    run_cmd( "cd $$config{cryosparc_directory} && tar -xzf $$config{cryosparc_downloads}/cryosparc_master.tar.gz" );
    print "first extraction complete\nstarting second extraction\n";
    run_cmd( "cd $$config{cryosparc_directory} && tar -xzf $$config{cryosparc_downloads}/cryosparc_worker.tar.gz" );
    print "second extraction complete\n";
    install();
}    

if ( !$extract
     &&
     ( !-d "$$config{cryosparc_directory}/cryosparc_master"
       ||  !-d "$$config{cryosparc_directory}/cryosparc_worker" ) ) {
    $extract = 1;
}

extract() if $extract;

if ( !$extract
     && !-e "$$config{cryosparc_directory}/cryosparc_master/config.sh" ) {
        install();
}

run_cmd( "$$config{cryosparc_directory}/cryosparc_master/bin/cryosparcm " . join( ' ', @ARGV ), 0, 0, 1 );
